### ISSUE TITLE
Need a UAP app that can cal the API

### ISSUE THREAD

**Issue by thebeebs** [thebeebs/microedgecase#2]
This app doesn't need to be IOT... Just an app that runs on desktop. The beauty of the UAP is that we should then be able to get that working on the PI.

The API is here:

http://edge.azurewebsites.net/api/v2/scan?url=http://www.bing.com

It accepts a URL and returns the Edge compatibility results. Users input the url without the http:// and usually without the www (all though not all the time)

So user should enter bing.com. And the apps should submit this to the API and get a response.

**Comment by jjcollinge** [comment]
I'm imagining there's a UI from the full scale one that we'll want to replicate? Is there any screen grabs or mock-ups available? Or is just a textbox and button all that's required for this?

**Comment by jjcollinge** [comment]
I'm assuming this is a headed application which will run on the Pi? Is there any screen grabs or UI mock ups from the full scale version that we'll want to replicate?

**Comment by liliankasem** [comment]
Happy to work on this with Joni
